version: '3.8'

services:
  # OpsGuide Java Application
  opsguide-java:
    build: .
    ports:
      - "8093:8093"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-mock}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-mock}
      - AWS_REGION=us-east-1
      - OPENSEARCH_ENDPOINT=http://opensearch:9200
      - OPENSEARCH_INDEX_NAME=knowledge-base
    depends_on:
      - opensearch
    networks:
      - opsguide-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8093/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # OpenSearch for Vector Search
  opensearch:
    image: opensearchproject/opensearch:2.11.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - opsguide-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # OpenSearch Dashboards (optional)
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.11.0
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
    depends_on:
      - opensearch
    networks:
      - opsguide-network

  # Redis for Caching (optional)
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - opsguide-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx Load Balancer (optional)
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - opsguide-java
    networks:
      - opsguide-network

networks:
  opsguide-network:
    driver: bridge

volumes:
  opensearch-data:
    driver: local
  redis-data:
    driver: local
